name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      pages_artifact_id: ${{ steps.upload_pages.outputs.artifact_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci
        working-directory: ./

      - name: Build Vite
        env:
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          VITE_BASE: ${{ vars.VITE_BASE }}
        run: |
          npm run build
          # SPA fallback (utile con react-router)
          cp dist/index.html dist/404.html
        working-directory: ./

      - name: Upload Pages artifact
        id: upload_pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the built site folder
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          # Disambiguate which artifact to deploy (fixes multiple artifacts error)
          artifact_id: ${{ needs.build.outputs.pages_artifact_id }}
